<?php
  // CODE SNIPPETS TO ADD TO 'wp-config.php' ON WORDPRESS
  
  // INCREASE MEMORY LIMIT
  define('WP_MEMORY_LIMIT', '256M');

  // EMPTY THE TRASH EVERY 5 DAYS
  define('EMPTY_TRASH_DAYS', 5 ); 

  // LIMIT POST REVISIONS TO 5
  define('WP_POST_REVISIONS', 5);

  // DISABLE POST REVISIONS
  define('WP_POST_REVISIONS', false);

  // AUTOSAVE ALL 5 MINUTES
  define('AUTOSAVE_INTERVAL', 300);
?>